sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - deps=""
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - composer update $COMPOSER_OPTIONS
